<template>
  <div class="page-shell page-shell-workspace">
    <div class="page-header">
      <div><h1 class="page-title">AI 智能运维 Agent</h1><p class="page-subtitle hidden sm:block">用自然语言查看纳管项目、提出配置变更并完成运维操作</p></div>
      <div class="page-actions flex-wrap">
        <label class="inline-flex items-center gap-2 text-xs text-zinc-400" title="开启后 Agent 可以检索 Docker、Compose 和软件官方资料"><Globe2 class="h-4 w-4" :class="webSearchEnabled ? 'text-cyan-400' : 'text-zinc-600'" /><input v-model="webSearchEnabled" type="checkbox" class="accent-cyan-500" />联网搜索</label>
        <select v-model="projectId" class="input w-full sm:w-auto" title="可选的当前项目上下文"><option value="">让 Agent 通过聊天识别项目</option><option v-for="project in projects" :key="project.id" :value="project.id">{{ project.projectName }}</option></select>
        <button class="btn-secondary" :disabled="loading" title="刷新纳管项目" @click="loadProjects"><RefreshCw class="h-4 w-4" :class="{ 'animate-spin': loading }" />刷新项目</button>
        <button v-if="running" class="btn-secondary !border-rose-900/60 !text-rose-300" title="中断当前 Agent 执行" @click="interrupt"><Square class="h-4 w-4" />中断</button>
      </div>
    </div>
    <div class="flex min-h-0 flex-1 flex-col gap-3 lg:flex-row">
      <main class="flex min-w-0 flex-1 flex-col gap-3">
        <section class="card flex min-h-[420px] flex-1 flex-col overflow-hidden">
          <div class="flex items-center justify-between border-b border-zinc-800 px-4 py-3"><div class="flex items-center gap-2 text-sm font-semibold text-zinc-200"><Bot class="h-4 w-4 text-cyan-400" />运维对话</div><span class="text-[11px] text-zinc-600">{{ webSearchEnabled ? '联网搜索已开启' : '联网搜索已关闭' }}</span></div>
          <div ref="scrollEl" class="min-h-0 flex-1 space-y-3 overflow-y-auto p-4">
            <div v-if="!messages.length" class="flex h-full flex-col items-center justify-center gap-3 text-center"><div class="grid h-12 w-12 place-items-center rounded-xl border border-zinc-800 bg-zinc-900 text-cyan-400"><MessageCircle class="h-6 w-6" /></div><h2 class="text-base font-semibold text-zinc-100">先问我有哪些项目可以操作</h2><p class="max-w-md text-sm leading-6 text-zinc-500">例如：查看已经纳管的项目，或者告诉我把生产项目 web 服务的端口改成 8081。</p><button class="preset-chip" @click="input = '查看我现在可以操作的项目'"><Sparkles class="h-3.5 w-3.5 text-cyan-400" />查看纳管项目</button></div>
            <div v-for="message in messages" :key="message.id" class="space-y-2">
              <div class="flex" :class="message.role === 'user' ? 'justify-end' : 'justify-start'"><div class="max-w-[90%] rounded-lg px-3 py-2 text-sm whitespace-pre-wrap break-words" :class="message.role === 'user' ? 'bg-cyan-950/40 text-zinc-100' : 'bg-zinc-900 text-zinc-300'">{{ message.content || (message.streaming ? '正在处理…' : '') }}</div></div>
              <div v-if="message.projects?.length" class="grid gap-2 sm:grid-cols-2"><div v-for="project in message.projects" :key="project.id" class="rounded-lg border border-zinc-800 bg-zinc-950/60 p-3"><div class="flex items-center justify-between gap-2"><strong class="truncate text-sm text-zinc-200">{{ project.name }}</strong><span class="text-[10px]" :class="project.editable ? 'text-emerald-400' : 'text-amber-400'">{{ project.editable ? '可编辑' : '仅容器控制' }}</span></div><p class="mt-1 text-xs text-zinc-500">{{ project.composeMode || 'containers' }} · {{ (project.services || []).length }} 个服务</p><button class="mt-2 text-xs text-cyan-400 hover:text-cyan-300" @click="selectProject(project)">在后续对话中使用</button></div></div>
              <div v-if="message.confirmation" class="rounded-lg border border-amber-900/60 bg-amber-950/20 p-3"><div class="flex items-start gap-2"><ShieldAlert class="mt-0.5 h-4 w-4 shrink-0 text-amber-400" /><div class="min-w-0"><div class="text-sm font-semibold text-amber-200">需要确认后执行</div><p class="mt-1 break-words text-xs text-amber-100/70">{{ message.confirmation.description || `确认执行 ${message.confirmation.tool}` }}</p><pre v-if="message.confirmation.params" class="mt-2 max-h-32 overflow-auto rounded bg-zinc-950/70 p-2 text-[11px] text-zinc-400">{{ stringify(message.confirmation.params) }}</pre></div></div><div class="mt-3 flex gap-2"><button class="btn-primary !py-1.5 !text-xs" :disabled="message.confirmation.busy" @click="approve(message)"><Check class="h-3.5 w-3.5" />确认执行</button><button class="btn-secondary !py-1.5 !text-xs" :disabled="message.confirmation.busy" @click="reject(message)">拒绝</button></div></div>
              <div v-if="message.searchSources?.length" class="rounded-lg border border-cyan-900/50 bg-cyan-950/10 p-3"><div class="mb-2 flex items-center gap-2 text-xs font-semibold text-cyan-300"><Globe2 class="h-3.5 w-3.5" />参考资料</div><a v-for="source in message.searchSources" :key="source.url || source.title" :href="source.url" target="_blank" rel="noreferrer" class="block truncate text-xs text-zinc-400 hover:text-cyan-300">{{ source.title || source.url || '搜索结果' }}</a></div>
              <div v-if="message.activity?.length" class="space-y-1 text-[11px] text-zinc-600"><div v-for="(item, index) in message.activity" :key="index"><span class="text-cyan-500">{{ item.label }}</span>{{ item.text }}</div></div>
            </div>
          </div>
          <div class="border-t border-zinc-800 p-3"><div class="flex gap-2"><textarea v-model="input" class="input min-w-0 flex-1 resize-none" rows="2" :disabled="running" placeholder="告诉 Agent 你想查看或操作什么…" @keydown.enter.exact.prevent="sendMessage"></textarea><button class="btn-primary shrink-0 self-end" :disabled="running || !input.trim()" @click="sendMessage"><Send class="h-4 w-4" />发送</button></div></div>
        </section>
      </main>
      <aside class="flex w-full shrink-0 flex-col gap-3 overflow-y-auto lg:w-80"><section class="card shrink-0 p-4"><h3 class="mb-2 text-sm font-semibold text-zinc-300">当前上下文</h3><p v-if="selectedProject" class="text-sm text-cyan-300">{{ selectedProject.projectName }}</p><p v-else class="text-xs leading-5 text-zinc-600">尚未固定项目。直接在聊天中说项目名称，Agent 会从纳管项目中识别。</p><button v-if="selectedProject" class="mt-2 text-xs text-zinc-500 hover:text-cyan-300" @click="projectId = ''">清除项目上下文</button></section><section class="card min-h-0 flex-1 p-4"><div class="mb-2 flex items-center justify-between"><h3 class="text-sm font-semibold text-zinc-300">执行动态</h3><span v-if="running" class="text-[10px] text-cyan-400">运行中</span></div><div class="space-y-2 overflow-y-auto text-xs"><div v-for="(item, index) in activity" :key="index"><span class="font-medium text-cyan-400">{{ item.label }}</span><p class="mt-0.5 text-zinc-500">{{ item.text }}</p></div><p v-if="!activity.length" class="text-zinc-600">发送消息后，这里会显示工具调用和确认状态。</p></div></section></aside>
    </div>
  </div>
</template>

<script setup>
import { computed, nextTick, onMounted, ref } from 'vue';
import { Bot, Check, Globe2, MessageCircle, RefreshCw, Send, ShieldAlert, Sparkles, Square } from 'lucide-vue-next';
import { api } from '../api/client.js';

const projects = ref([]); const projectId = ref(''); const input = ref(''); const messages = ref([]); const activity = ref([]); const loading = ref(false); const running = ref(false); const webSearchEnabled = ref(false); const scrollEl = ref(null);
let nextId = 0; let controller = null; let activeAssistant = null;
const selectedProject = computed(() => projects.value.find((project) => project.id === projectId.value));
function stringify(value) { try { return JSON.stringify(value, null, 2); } catch { return String(value); } }
function appendActivity(label, text) { const item = { label, text: String(text || '') }; activity.value.push(item); if (activeAssistant) { activeAssistant.activity ||= []; activeAssistant.activity.push(item); } }
function scrollBottom() { void nextTick(() => { if (scrollEl.value) scrollEl.value.scrollTop = scrollEl.value.scrollHeight; }); }
async function loadProjects() { loading.value = true; try { projects.value = ((await api.getProjects(true)).projects || []).filter((project) => project.managed); } catch { projects.value = []; } finally { loading.value = false; } }
function selectProject(project) { projectId.value = project.id; input.value = `后续操作项目 ${project.name}`; }
function historyForRequest() { return messages.value.filter((message) => ['user', 'assistant'].includes(message.role) && message.content).slice(-12).map(({ role, content }) => ({ role, content: content.slice(0, 12000) })); }
async function sendMessage() { const text = input.value.trim(); if (!text || running.value) return; input.value = ''; const user = { id: ++nextId, role: 'user', content: text }; const assistant = { id: ++nextId, role: 'assistant', content: '', streaming: true, activity: [] }; messages.value.push(user, assistant); activeAssistant = assistant; running.value = true; activity.value = []; controller = new AbortController(); scrollBottom(); try { await api.agentExecuteStream({ message: text, projectId: projectId.value || undefined, sessionId: 0, role: 'planner', webSearchEnabled: webSearchEnabled.value, history: historyForRequest().slice(0, -1) }, (event) => handleEvent(event, assistant), controller.signal); } catch (error) { if (error.name !== 'AbortError') assistant.content = `执行失败：${error.message}`; } finally { assistant.streaming = false; running.value = false; controller = null; activeAssistant = null; scrollBottom(); } }
function handleEvent(event, assistant) { if (event.type === 'thought') assistant.content += event.content || ''; else if (event.type === 'loop_started') appendActivity('已连接 ', `${event.role || 'Agent'}，可用工具 ${event.toolsAvailable || 0} 个`); else if (event.type === 'tool_requested') appendActivity('请求工具 ', event.tool); else if (event.type === 'tool_executing') appendActivity('执行工具 ', event.tool); else if (event.type === 'tool_result') { appendActivity('工具完成 ', event.tool); const payload = event.result?.result; if (event.tool === 'project.list_managed' && Array.isArray(payload)) assistant.projects = payload; if (event.tool === 'web.search' && Array.isArray(payload?.sources)) assistant.searchSources = payload.sources; } else if (event.type === 'confirmation_required') { assistant.confirmation = { ...event, busy: false }; appendActivity('等待确认 ', event.tool); } else if (event.type === 'tool_rejected') appendActivity('已拒绝 ', event.tool); else if (event.type === 'tool_error') appendActivity('工具错误 ', event.error); else if (event.type === 'interrupted') assistant.content = event.reason || '执行已中断'; else if (event.type === 'error') assistant.content = event.content || 'Agent 执行失败'; else if (event.type === 'done' && event.content) assistant.content = event.content; scrollBottom(); }
async function approve(message) { const confirmation = message.confirmation; if (!confirmation || confirmation.busy) return; confirmation.busy = true; try { await api.agentApprove({ executionId: confirmation.executionId, toolCallId: confirmation.toolCallId, approved: true }); message.confirmation = null; appendActivity('已确认 ', confirmation.tool); } catch (error) { confirmation.busy = false; message.content = `确认失败：${error.message}`; } }
async function reject(message) { const confirmation = message.confirmation; if (!confirmation || confirmation.busy) return; confirmation.busy = true; try { await api.agentApprove({ executionId: confirmation.executionId, toolCallId: confirmation.toolCallId, approved: false }); message.confirmation = null; appendActivity('已拒绝 ', confirmation.tool); } catch (error) { confirmation.busy = false; message.content = `拒绝失败：${error.message}`; } }
function interrupt() { controller?.abort(); }
onMounted(loadProjects);
</script>
